### ISSUE TITLE
Plugin doessn't recognize existing cluster and creates a duplicate

### ISSUE THREAD

**Issue by carolynvs** [jupyterhub/jupyterhub-carina#7]
When I delete the jupyterhub container for a user, and then attempt to start the server, instead of recreating the container, it tries to create a new cluster. It is not finding the existing cluster and reusing it.

```
[E 2017-01-30 17:47:37.596 JupyterHub web:1548] Uncaught exception GET /jupyter/hub/user/carolynvs (108.166.30.187)
    Traceback (most recent call last):
      File "/opt/conda/lib/python3.5/site-packages/tornado/web.py", line 1469, in _execute
        result = yield result
      File "/opt/conda/lib/python3.5/site-packages/jupyterhub/handlers/base.py", line 484, in get
        yield self.spawn_single_user(current_user)
      File "/opt/conda/lib/python3.5/site-packages/jupyterhub/handlers/base.py", line 306, in spawn_single_user
        yield gen.with_timeout(timedelta(seconds=self.slow_spawn_timeout), f)
      File "/opt/conda/lib/python3.5/site-packages/jupyterhub/user.py", line 245, in spawn
        raise e
      File "/opt/conda/lib/python3.5/site-packages/jupyterhub/user.py", line 226, in spawn
        yield gen.with_timeout(timedelta(seconds=spawner.start_timeout), f)
      File "/srv/jupyterhub/src/jupyterhub-carina/jupyterhub_carina/CarinaSpawner.py", line 151, in start
        cluster = yield self.create_cluster()
      File "/srv/jupyterhub/src/jupyterhub-carina/jupyterhub_carina/CarinaSpawner.py", line 169, in create_cluster
        return (yield self.carina_client.create_cluster(self.cluster_name))
      File "/srv/jupyterhub/src/jupyterhub-carina/jupyterhub_carina/CarinaOAuthClient.py", line 120, in create_cluster
        response = yield self.execute_oauth_request(request)
      File "/srv/jupyterhub/src/jupyterhub-carina/jupyterhub_carina/CarinaOAuthClient.py", line 244, in execute_oauth_request
        return (yield self.execute_request(request, raise_error))
      File "/srv/jupyterhub/src/jupyterhub-carina/jupyterhub_carina/CarinaOAuthClient.py", line 275, in execute_request
        return (yield http_client.fetch(request, raise_error=raise_error))
    tornado.httpclient.HTTPError: HTTP 413: Payload Too Large
```

The Carina API in this case is returning 413 Payload Too Large, indicating that I've hit my 3 cluster quota. If I had had fewer clusters, it would have made a duplicate cluster with the same name.

**Comment by carolynvs** [comment]
Oops, I should have realized this would be a problem! The old Carina would ignore requests to create a new cluster, if one already existed with the same name. Now that you can create multiple  clusters with the same name, I need to check for it and reuse the cluster if found.
